version: '3.8'

networks:
  infra:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - infra

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hospital
      - MYSQL_USER=alexandre
      - MYSQL_PASSWORD=root
    ports:
      - "3356:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - infra
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - infra

volumes:
  esdata1:
  mysqldata:
